<a href="https://colab.research.google.com/github/esinam-kekele/ghana-energy-demand-forecast/blob/main/src/train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro

Starting with public dataset first since it's difficult to get Ghana Open Data Sources. However i'm looking at potential sources such as:

- Energy Commission Ghana -> - https://www.energycom.gov.gh?utm_source=chatgpt.com
- Volta River Authority -> https://www.energycom.gov.gh?utm_source=chatgpt.com
- GRIDCo Ghana->https://www.gridcogh.com?utm_source=chatgpt.com

However, publicly available historical demand data may be limited and so i'm using the alternative public electricity demand dataset first on Kaggle and once it works, i will look at implementing it for Ghana.

For this project, i will be considering either the:

PJM
- PJM Hourly Energy Consumption Dataset -> https://archive.ics.uci.edu/ml/datasets/ElectricityLoadDiagrams20112014?utm_source=chatgpt.com

or the

Electricity Load Diagrams
- UCI Electricity Load Diagrams Dataset -> https://archive.ics.uci.edu/ml/datasets/ElectricityLoadDiagrams20112014?utm_source=chatgpt.com

Why these dataset?
Because:
- Clean
- Large
- Well-known

for now, i will focus on forecasting, then later adapt methodology to Ghana.

import kagglehub

# Download latest version
path = kagglehub.dataset_download("robikscube/hourly-energy-consumption")

print("Path to dataset files:", path)

## Get Data

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("robikscube/hourly-energy-consumption")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'hourly-energy-consumption' dataset.
Path to dataset files: /kaggle/input/hourly-energy-consumption

In [2]:
import os

for file in os.listdir(path):
    print(file)

est_hourly.paruqet
DOM_hourly.csv
EKPC_hourly.csv
DUQ_hourly.csv
DAYTON_hourly.csv
PJME_hourly.csv
PJM_Load_hourly.csv
NI_hourly.csv
FE_hourly.csv
COMED_hourly.csv
AEP_hourly.csv
pjm_hourly_est.csv
DEOK_hourly.csv
PJMW_hourly.csv

## Load PJM Dataset

In [3]:
import pandas as pd

df = pd.read_csv(
    os.path.join(path, "PJM_Load_hourly.csv")
)

df.head()

              Datetime  PJM_Load_MW
0  1998-12-31 01:00:00      29309.0
1  1998-12-31 02:00:00      28236.0
2  1998-12-31 03:00:00      27692.0
3  1998-12-31 04:00:00      27596.0
4  1998-12-31 05:00:00      27888.0

In [4]:
print(f"Shape: {df.shape}")

Shape: (32896, 2)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32896 entries, 0 to 32895
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Datetime     32896 non-null  object
 1   PJM_Load_MW  32896 non-null  float64
dtypes: float64(1), object(1)
memory usage: 514.1+ KB

In [6]:
df.describe()

        PJM_Load_MW
count  32896.000000
mean   29766.427408
std     5849.769954
min    17461.000000
25%    25473.000000
50%    29655.000000
75%    33073.250000
max    54030.000000

In [7]:
df.isnull().sum()

Datetime       0
PJM_Load_MW    0
dtype: int64

In [8]:
df = df.set_index("Datetime")

df.head()

                     PJM_Load_MW
Datetime
1998-12-31 01:00:00      29309.0
1998-12-31 02:00:00      28236.0
1998-12-31 03:00:00      27692.0
1998-12-31 04:00:00      27596.0
1998-12-31 05:00:00      27888.0

## Visualize Electricity Demand

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(15,5))

plt.plot(df.index, df["PJM_Load_MW"])

plt.title("PJM Hourly Energy Consumption")
plt.xlabel("Date")
plt.ylabel("Load (MW)")

plt.show()